! this file was generated by tpled

level Phoneme 
level Target 




labfile Phoneme :type SEGMENT :extension phon :time-factor 1000 
labfile Target :type EVENT :extension targ :time-factor 1000 


legal Phoneme short E
 
legal Phoneme short A
 
legal Phoneme short V
 
legal Phoneme short O
 
legal Phoneme short U
 
legal Phoneme short I
 
legal Phoneme long i:
 
legal Phoneme long a:
 
legal Phoneme long o:
 
legal Phoneme long u:
 
legal Phoneme long @:
 



path phon G:\summer_research\voice_recordings\Y22F
path targ G:\summer_research\voice_recordings\Y22F
path hlb G:\summer_research\voice_recordings\Y22F
path wav G:\summer_research\voice_recordings\Y22F
path sfb G:\summer_research\voice_recordings\Y22F
path sf0 G:\summer_research\voice_recordings\Y22F


track samples wav
track fm sfb
track F0 sf0


set PrimaryExtension wav
set LabelTracks samples spectrogram fm 
set SpectrogramWhiteLevel -20
set HierarchyViewLevels Phoneme Target 
set SignalViewLevels Phoneme Target 

 
