! this file was generated by Moa 
 
path lab C:\Users\Govindu\Dropbox\P4P\p4p\TestDB\System.Collections.Generic.List`1[System.String]\*
path trg C:\Users\Govindu\Dropbox\P4P\p4p\TestDB\System.Collections.Generic.List`1[System.String]\*
path hlb C:\Users\Govindu\Dropbox\P4P\p4p\TestDB\System.Collections.Generic.List`1[System.String]\*
path wav C:\Users\Govindu\Dropbox\P4P\p4p\TestDB\System.Collections.Generic.List`1[System.String]\*
path sfb C:\Users\Govindu\Dropbox\P4P\p4p\TestDB\System.Collections.Generic.List`1[System.String]\*
 
track samples wav
track k1 sf0

set PrimaryExtension wav 
