! this file was generated by tpled

level Utterance 
level Word Utterance 
level Phoneme Word 
level Phonetic Phoneme 
level Target Phonetic 


label Utterance Utterance 
label Utterance Talker 
label Utterance Sex 

label Phoneme Phoneme 

label Phonetic Phonetic 

label Target Target 



labfile Phonetic :type SEGMENT :extension lab :time-factor 1000 
labfile Target :type EVENT :extension trg :time-factor 1000 


legal Phonetic vowel A E I O V U ai ei oi i@ u@ e@ au @u @: @ a: e: i: o: u:
 
legal Phonetic stop p tS dZ t k b d g
 
legal Phonetic nasal m n 9
 
legal Phonetic fricative f v s z S Z h D T
 
legal Phonetic approximant w j l r rr Or
 
 
legal Phonetic other H #
 
 


path lab C:/Catherine/research/Aging/acoustic_tubes/Recordings for the AR expt/*
path trg C:/Catherine/research/Aging/acoustic_tubes/Recordings for the AR expt/*
path hlb C:/Catherine/research/Aging/acoustic_tubes/Recordings for the AR expt/*
path wav C:/Catherine/research/Aging/acoustic_tubes/Recordings for the AR expt/*
path sfb C:/Catherine/research/Aging/acoustic_tubes/Recordings for the AR expt/*


track samples wav
track fm sfb
track bw sfb


set PrimaryExtension wav
set LabelTracks samples spectrogram fm 
set SpectrogramWhiteLevel -20
set AutoBuild building_nzaging.tcl
set HierarchyViewLevels Utterance Word Phonetic Target 
set SignalViewLevels Utterance Word Phonetic Target 

 
